#!/bin/bash

rostopic pub /simulation/right_arm/settings/switch_mode -1 std_msgs/Int32 10 &
rostopic pub /simulation/left_arm/settings/switch_mode -1 std_msgs/Int32 10 &
rostopic pub /simulation/right_arm/joint_control/set_velocity_limit -1 std_msgs/Float32 1.0 & 
rostopic pub /simulation/left_arm/joint_control/set_velocity_limit -1 std_msgs/Float32 1.0 & 